#' Build epidemic-level DLNM design matrix
#'
#' Constructs an epidemic-level design matrix from exposure histories
#' stored in long format.
#'
#' The input data must contain:
#' - `epi_id`: epidemic identifier
#' - `time`: time index
#'
#' Exposure histories must be supplied in chronological order,
#' from the earliest observation to the most recent observation
#' prior to disease assessment.
#'
#' Internal conversion to DLNM lag representation is handled
#' automatically through the cross-basis construction.
#'
#' @param data Long-format exposure dataset.
#' @param cb_templates DLNM templates generated by `define_exposure()`.
#' @param max_lag Maximum lag.
#' @param include_response Logical. If `TRUE`, include response variable
#'   (`y`) when available.
#'
#' @return Epidemic-level design matrix.
#'
#' @export
build_design <- function(
    data,
    cb_templates,
    max_lag,
    include_response = TRUE
) {

  # =========================================================
  # ✅ TEMPORAL DIMENSION
  # =========================================================

  max_lag <- as.integer(max(max_lag))

  # =========================================================
  # ✅ BASIC CHECKS
  # =========================================================

  stopifnot("epi_id" %in% names(data))
  stopifnot("time" %in% names(data))

  for (v in names(cb_templates)) {

    if (!v %in% names(data)) {

      stop(
        paste0(
          "Variable '",
          v,
          "' not found in data. Available variables: ",
          paste(names(data), collapse = ", ")
        )
      )
    }
  }

  `%||%` <- function(a, b) {
    if (!is.null(a)) a else b
  }

  # =========================================================
  # ✅ TEMPORAL COVERAGE CHECK
  # =========================================================

  .check_lag_coverage <- function(dat, max_lag) {

    n_required <- max_lag + 1L

    bad_ids <- dat |>
      dplyr::group_by(epi_id) |>
      dplyr::summarise(
        n_time = dplyr::n_distinct(time),
        .groups = "drop"
      ) |>
      dplyr::filter(n_time < n_required)

    if (nrow(bad_ids) > 0) {

      stop(
        paste0(
          "Some epidemics do not have enough temporal coverage for max_lag.\n",
          "Required observations per epi_id: ",
          n_required,
          "\n",
          "Example problematic epi_id: ",
          paste(head(bad_ids$epi_id, 5), collapse = ", ")
        )
      )
    }

    invisible(TRUE)
  }

  .check_lag_coverage(data, max_lag)

  # =========================================================
  # STORE ACTUAL CROSS-BASIS OBJECTS
  # =========================================================

  cb_templates_used <- list()

  extract_last_cb_row <- function(
    x,
    cb_template,
    var_name
  ) {

    cb <- dlnm::crossbasis(
      x,
      lag    = max_lag,
      argvar = attr(cb_template, "argvar"),
      arglag = attr(cb_template, "arglag")
    )

    if (is.null(cb_templates_used[[var_name]])) {
      cb_templates_used[[var_name]] <<- cb
    }

    cn <- colnames(cb)

    if (is.null(cn)) {

      cn <- paste0(
        "cb_",
        var_name,
        "_",
        seq_len(ncol(cb))
      )

    } else {

      cn <- paste0(
        "cb_",
        var_name,
        "_",
        seq_len(length(cn))
      )
    }

    out <- as.numeric(
      cb[length(x), ]
    )

    names(out) <- cn

    out
  }

  # =========================================================
  # ✅ BUILD DESIGN MATRIX
  # =========================================================

  X_list <- purrr::imap(
    cb_templates,
    function(cb, v) {

      tmp <- data |>
        dplyr::group_by(epi_id) |>
        dplyr::arrange(time, .by_group = TRUE) |>
        dplyr::summarise(
          cb = list(
            extract_last_cb_row(
              .data[[v]],
              cb,
              v
            )
          ),
          .groups = "drop"
        )

      tmp |>
        tidyr::unnest_wider(cb)
    }
  )

  out <- purrr::reduce(
    X_list,
    dplyr::left_join,
    by = "epi_id"
  )

  # =========================================================
  # ✅ INCLUDE RESPONSE VARIABLE
  # =========================================================

  if (
    isTRUE(include_response) &&
    "y" %in% names(data)
  ) {

    y_df <- data |>
      dplyr::distinct(
        epi_id,
        y
      )

    if (any(duplicated(y_df$epi_id))) {

      stop(
        "Multiple 'y' values per epi_id detected. ",
        "Expected one y per epidemic."
      )
    }

    if (
      nrow(y_df) !=
      length(unique(data$epi_id))
    ) {

      stop(
        "Mismatch between epi_id and y values."
      )
    }

    out <- dplyr::left_join(
      out,
      y_df,
      by = "epi_id"
    )
  }

  # =========================================================
  # ✅ SAVE CROSS-BASIS OBJECTS
  # =========================================================

  attr(
    out,
    "cb_templates"
  ) <- cb_templates_used

  out
}
