#' Plot predictions across epidemiological scenarios
#'
#' Plots predictions generated by `simulate_scenarios()` across a scenario
#' variable. The default sample-level plot reproduces the EpiExposure scenario
#' visualization based on `geom_smooth()`, `scale_color_viridis_c()`,
#' `theme_bw()`, bold text, white facet strips, and no legend.
#'
#' @param data A non-empty data frame returned by `simulate_scenarios()`.
#' @param x Character scalar naming the scenario variable on the x-axis.
#' @param y Character scalar naming the prediction column. Default is
#'   `"prediction"`.
#' @param facet Optional character vector naming the variables used by
#'   `ggplot2::facet_wrap()`, for example `c("wetness", "tmean")`.
#' @param sample Character scalar naming the sample identifier. Default is
#'   `"sample"`.
#' @param lower,upper Character scalars naming lower and upper uncertainty limits
#'   for summary output.
#' @param mode Character. `"auto"`, `"samples"`, or `"summary"`. In automatic
#'   mode, sample mode is used when the sample column is present.
#' @param scale_factor Finite numeric multiplier applied to predictions and
#'   interval limits. Use `100` to display proportions as percentages.
#' @param facet_ncol,facet_nrow Optional positive integers controlling the facet
#'   arrangement.
#' @param color_scale Optional ggplot2 color scale for sample-level trajectories.
#'   The default is `ggplot2::scale_color_viridis_c()`.
#' @param color_label Legend title used by the default color scale.
#' @param line_color Color of the central line in summary mode.
#' @param ribbon_fill,ribbon_alpha Fill and transparency of the summary
#'   uncertainty ribbon.
#' @param show_ribbon Logical. Display the uncertainty ribbon when summary
#'   interval columns are available.
#' @param smooth Logical. Use `ggplot2::geom_smooth()` when `TRUE` and
#'   `ggplot2::geom_line()` when `FALSE`.
#' @param smooth_method Optional smoothing method passed to `geom_smooth()`.
#'   When `NULL`, ggplot2 selects its default method, exactly as in a direct
#'   `geom_smooth()` call.
#' @param smooth_formula Optional formula passed to `geom_smooth()`.
#' @param smooth_se Logical. Display the smoothing standard-error band. Default
#'   is `FALSE`.
#' @param line_width Optional positive line width. When `NULL`, the ggplot2
#'   default is used.
#' @param line_alpha Line transparency between 0 and 1.
#' @param x_breaks,y_breaks Optional numeric axis breaks.
#' @param x_limits,y_limits Optional numeric vectors of length two.
#' @param x_expand,y_expand Axis expansion specifications.
#' @param x_label,y_label Axis titles. Defaults are `"Exposure"` and
#'   `"Predicted"`, matching the original EpiExposure scenario plot.
#' @param title,subtitle,caption Optional plot annotations.
#' @param theme Optional ggplot2 theme. When `NULL`, `ggplot2::theme_bw()` is
#'   used without replacing its default panel grid.
#' @param base_size Base text size. Default is 10.
#' @param text_face Common text face. Default is `"bold"`.
#' @param axis_title_size Axis-title size. Default is 12.
#' @param strip_background Facet-strip background element.
#' @param legend_position Legend position. Default is `"none"`.
#' @param line_args Optional named list of additional arguments passed to the
#'   trajectory layer.
#' @param ribbon_args Optional named list of arguments passed to
#'   `ggplot2::geom_ribbon()`.
#' @param add Optional ggplot2 component or list of components added last.
#' @param ... Additional named arguments passed to the trajectory layer.
#'
#' @return A `ggplot` object.
#'
#' @details
#' In sample mode, the grouping aesthetic is exactly the sample identifier,
#' matching `aes(group = sample, color = sample)`. Faceting does not alter the
#' grouping variable. Facet variables are combined using a formula equivalent to
#' `facet_wrap(~ wetness + tmean)`.
#'
#' @examples
#' \dontrun{
#' plot_scenarios(
#'   data = pred_scenarios,
#'   x = "rain",
#'   facet = c("wetness", "tmean"),
#'   scale_factor = 100,
#'   x_limits = c(0, 15)
#' )
#' }
#'
#' @export
plot_scenarios <- function(
    data,
    x,
    y = "prediction",
    facet = NULL,
    sample = "sample",
    lower = "lower",
    upper = "upper",
    mode = c("auto", "samples", "summary"),
    scale_factor = 1,
    facet_ncol = NULL,
    facet_nrow = NULL,
    color_scale = NULL,
    color_label = "Sample",
    line_color = "black",
    ribbon_fill = "grey70",
    ribbon_alpha = 0.25,
    show_ribbon = TRUE,
    smooth = TRUE,
    smooth_method = NULL,
    smooth_formula = NULL,
    smooth_se = FALSE,
    line_width = NULL,
    line_alpha = 1,
    x_breaks = NULL,
    y_breaks = NULL,
    x_limits = NULL,
    y_limits = NULL,
    x_expand = ggplot2::expansion(mult = c(0.01, 0.01)),
    y_expand = ggplot2::waiver(),
    x_label = "Exposure",
    y_label = "Predicted",
    title = NULL,
    subtitle = NULL,
    caption = NULL,
    theme = NULL,
    base_size = 10,
    text_face = "bold",
    axis_title_size = 12,
    strip_background = ggplot2::element_rect(fill = "white", colour = "black"),
    legend_position = "none",
    line_args = list(),
    ribbon_args = list(),
    add = NULL,
    ...
) {
  if (!requireNamespace("ggplot2", quietly = TRUE)) {
    stop("Package 'ggplot2' is required by `plot_scenarios()`.", call. = FALSE)
  }

  scalar_name <- function(z) {
    is.character(z) && length(z) == 1L && !is.na(z) && nzchar(z)
  }
  scalar_flag <- function(z) {
    is.logical(z) && length(z) == 1L && !is.na(z)
  }
  positive_integer_or_null <- function(z, argument) {
    if (is.null(z)) return(NULL)
    if (!is.numeric(z) || length(z) != 1L || is.na(z) ||
        !is.finite(z) || z < 1 || z != as.integer(z)) {
      stop("`", argument, "` must be NULL or a positive integer.", call. = FALSE)
    }
    as.integer(z)
  }
  named_list <- function(z, argument) {
    if (!is.list(z)) stop("`", argument, "` must be a list.", call. = FALSE)
    if (length(z) && (is.null(names(z)) || anyNA(names(z)) ||
                      any(!nzchar(names(z))))) {
      stop("Every entry in `", argument, "` must be named.", call. = FALSE)
    }
    z
  }
  add_components <- function(plot_object, components) {
    if (is.null(components)) return(plot_object)
    if (!is.list(components) ||
        inherits(components, c("gg", "ggplot", "Scale", "theme", "Coord"))) {
      components <- list(components)
    }
    for (component in components) plot_object <- plot_object + component
    plot_object
  }

  if (!is.data.frame(data) || !nrow(data)) {
    stop("`data` must be a non-empty data frame returned by `simulate_scenarios()`.",
         call. = FALSE)
  }
  for (argument in c("x", "y", "sample", "lower", "upper")) {
    if (!scalar_name(get(argument, inherits = FALSE))) {
      stop("`", argument, "` must be one non-empty column name.", call. = FALSE)
    }
  }
  if (!is.null(facet) &&
      (!is.character(facet) || !length(facet) || anyNA(facet) ||
       any(!nzchar(facet)) || anyDuplicated(facet))) {
    stop("`facet` must be NULL or unique non-empty column names.", call. = FALSE)
  }

  mode <- match.arg(mode)
  if (mode == "auto") mode <- if (sample %in% names(data)) "samples" else "summary"

  required <- unique(c(x, y, facet, if (mode == "samples") sample))
  missing_columns <- setdiff(required, names(data))
  if (length(missing_columns)) {
    stop("Column(s) missing from `data`: ",
         paste(missing_columns, collapse = ", "), ".", call. = FALSE)
  }

  for (column in c(x, y)) {
    if (!is.numeric(data[[column]]) || anyNA(data[[column]]) ||
        any(!is.finite(data[[column]]))) {
      stop("Column '", column, "' must contain finite numeric values.",
           call. = FALSE)
    }
  }

  if (!is.numeric(scale_factor) || length(scale_factor) != 1L ||
      is.na(scale_factor) || !is.finite(scale_factor)) {
    stop("`scale_factor` must be one finite number.", call. = FALSE)
  }
  for (argument in c("show_ribbon", "smooth", "smooth_se")) {
    if (!scalar_flag(get(argument, inherits = FALSE))) {
      stop("`", argument, "` must be TRUE or FALSE.", call. = FALSE)
    }
  }
  if (!is.null(line_width) &&
      (!is.numeric(line_width) || length(line_width) != 1L ||
       is.na(line_width) || !is.finite(line_width) || line_width <= 0)) {
    stop("`line_width` must be NULL or one positive finite number.", call. = FALSE)
  }
  if (!is.numeric(line_alpha) || length(line_alpha) != 1L ||
      is.na(line_alpha) || !is.finite(line_alpha) ||
      line_alpha < 0 || line_alpha > 1) {
    stop("`line_alpha` must be between 0 and 1.", call. = FALSE)
  }
  if (!is.numeric(ribbon_alpha) || length(ribbon_alpha) != 1L ||
      is.na(ribbon_alpha) || !is.finite(ribbon_alpha) ||
      ribbon_alpha < 0 || ribbon_alpha > 1) {
    stop("`ribbon_alpha` must be between 0 and 1.", call. = FALSE)
  }

  facet_ncol <- positive_integer_or_null(facet_ncol, "facet_ncol")
  facet_nrow <- positive_integer_or_null(facet_nrow, "facet_nrow")
  line_args <- named_list(line_args, "line_args")
  ribbon_args <- named_list(ribbon_args, "ribbon_args")
  dots <- named_list(list(...), "...")

  if (!is.null(color_scale) && !inherits(color_scale, "Scale")) {
    stop("`color_scale` must be NULL or a ggplot2 color scale.", call. = FALSE)
  }

  plot_data <- data
  plot_data$.plot_x <- plot_data[[x]]
  plot_data$.plot_y <- plot_data[[y]] * scale_factor

  if (mode == "samples") {
    sample_values <- plot_data[[sample]]
    sample_numeric <- suppressWarnings(as.numeric(as.character(sample_values)))
    if (anyNA(sample_numeric)) {
      sample_numeric <- as.numeric(factor(sample_values, levels = unique(sample_values)))
    }
    plot_data$.plot_sample <- sample_numeric
    plot_data$.plot_group <- plot_data[[sample]]
  }

  has_interval <- mode == "summary" && show_ribbon &&
    all(c(lower, upper) %in% names(plot_data))
  if (has_interval) {
    for (column in c(lower, upper)) {
      if (!is.numeric(plot_data[[column]]) || anyNA(plot_data[[column]]) ||
          any(!is.finite(plot_data[[column]]))) {
        stop("Interval column '", column,
             "' must contain finite numeric values.", call. = FALSE)
      }
    }
    plot_data$.plot_lower <- plot_data[[lower]] * scale_factor
    plot_data$.plot_upper <- plot_data[[upper]] * scale_factor
    if (any(plot_data$.plot_lower > plot_data$.plot_upper)) {
      stop("Every lower interval value must be less than or equal to upper.",
           call. = FALSE)
    }
  }

  plot_object <- ggplot2::ggplot(plot_data)

  if (has_interval) {
    ribbon_layer <- list(
      mapping = ggplot2::aes(
        x = .data$.plot_x,
        ymin = .data$.plot_lower,
        ymax = .data$.plot_upper
      ),
      fill = ribbon_fill,
      alpha = ribbon_alpha,
      inherit.aes = FALSE
    )
    ribbon_layer[names(ribbon_args)] <- ribbon_args
    plot_object <- plot_object + do.call(ggplot2::geom_ribbon, ribbon_layer)
  }

  trajectory_args <- dots
  trajectory_args[names(line_args)] <- line_args
  trajectory_args$se <- if (smooth) smooth_se else NULL
  trajectory_args$alpha <- line_alpha
  if (!is.null(line_width)) trajectory_args$linewidth <- line_width

  if (mode == "samples") {
    trajectory_args$mapping <- ggplot2::aes(
      x = .data$.plot_x,
      y = .data$.plot_y,
      group = .data$.plot_group,
      colour = .data$.plot_sample
    )
  } else {
    trajectory_args$mapping <- ggplot2::aes(
      x = .data$.plot_x,
      y = .data$.plot_y
    )
    trajectory_args$colour <- line_color
  }

  if (smooth) {
    if (!is.null(smooth_method)) trajectory_args$method <- smooth_method
    if (!is.null(smooth_formula)) trajectory_args$formula <- smooth_formula
    plot_object <- plot_object + do.call(ggplot2::geom_smooth, trajectory_args)
  } else {
    trajectory_args$se <- NULL
    plot_object <- plot_object + do.call(ggplot2::geom_line, trajectory_args)
  }

  if (mode == "samples") {
    if (is.null(color_scale)) {
      color_scale <- ggplot2::scale_color_viridis_c(name = color_label)
    }
    plot_object <- plot_object + color_scale
  }

  plot_object <- plot_object +
    ggplot2::theme_bw() +
    ggplot2::labs(
      x = x_label,
      y = y_label,
      title = title,
      subtitle = subtitle,
      caption = caption
    ) +
    ggplot2::theme(
      text = ggplot2::element_text(size = base_size, face = text_face),
      axis.title = ggplot2::element_text(
        size = axis_title_size,
        face = text_face
      ),
      strip.background = strip_background,
      legend.position = legend_position
    )

  if (length(facet)) {
    facet_formula <- stats::reformulate(facet)
    plot_object <- plot_object + ggplot2::facet_wrap(
      facet_formula,
      ncol = facet_ncol,
      nrow = facet_nrow
    )
  }

  plot_object <- plot_object +
    ggplot2::scale_x_continuous(
      breaks = x_breaks,
      limits = x_limits,
      expand = x_expand
    ) +
    ggplot2::scale_y_continuous(
      breaks = y_breaks,
      limits = y_limits,
      expand = y_expand
    )

  if (!is.null(theme)) plot_object <- plot_object + theme
  add_components(plot_object, add)
}
