#' Plot predictions across epidemiological scenarios
#'
#' Plot predictions generated by `simulate_scenarios()` while respecting both
#' the scenario design created by `simulate_ranges()` (`"grid"` or `"paired"`)
#' and the prediction output returned by `simulate_scenarios()` (`"samples"` or
#' `"summary"`).
#'
#' The default plotting behavior is:
#'
#' * `scenario_type = "grid"` + `output = "samples"`:
#'   sample-specific trajectories using `geom_smooth()` (or `geom_line()`).
#' * `scenario_type = "grid"` + `output = "summary"`:
#'   one central trajectory, optionally with a lower/upper uncertainty ribbon.
#' * `scenario_type = "paired"` + `output = "samples"`:
#'   the distribution of sample predictions at each paired scenario using
#'   `geom_boxplot()` by default.
#' * `scenario_type = "paired"` + `output = "summary"`:
#'   point estimates and lower/upper uncertainty intervals using
#'   `geom_pointrange()`.
#'
#' @param data A non-empty data frame returned by `simulate_scenarios()`.
#'
#' @param x Character scalar naming the scenario variable shown on the x-axis.
#'
#' @param scenario_type Character. Scenario design used to generate the
#'   scenarios in `simulate_ranges()`. Must be `"grid"` or `"paired"`.
#'   Default is `"grid"`.
#'
#' @param output Character. Prediction output represented by `data`:
#'   `"auto"`, `"samples"`, or `"summary"`.
#'
#'   With `"auto"` (default), the function identifies `"samples"` when the
#'   column named by `sample` is present; otherwise it uses `"summary"`.
#'   This mirrors the two output structures returned by
#'   `simulate_scenarios()`.
#'
#' @param mode Deprecated compatibility alias for `output`. It is retained so
#'   calls written for earlier versions of `plot_scenarios()` do not break.
#'   New code should use `output`. Do not supply both `output` and `mode`.
#'
#' @param y Character scalar naming the prediction column. Default is
#'   `"prediction"`.
#'
#' @param facet Optional character vector naming variables used by
#'   `ggplot2::facet_wrap()`, for example `c("wetness", "tmean")`.
#'
#' @param sample Character scalar naming the sample identifier in
#'   `output = "samples"`. Default is `"sample"`.
#'
#' @param lower,upper Optional character scalars naming the lower and upper
#'   uncertainty-limit columns in `output = "summary"`.
#'
#'   When left as `NULL`, `plot_scenarios()` looks first for
#'   `"prediction_lower"` and `"prediction_upper"`, respectively, and then for
#'   `"lower"` and `"upper"`.
#'
#'   These arguments are not used for `output = "samples"` because sample-level
#'   output contains individual prediction draws rather than pre-computed
#'   lower/upper limits.
#'
#' @param scale_factor Finite numeric multiplier applied to predictions and,
#'   when present, lower and upper limits. Use `100` to display proportions as
#'   percentages.
#'
#' @param facet_ncol,facet_nrow Optional positive integers controlling the facet
#'   arrangement.
#'
#' @param color_scale Optional ggplot2 color scale used for sample-specific grid
#'   trajectories. When `NULL`, `ggplot2::scale_color_viridis_c()` is used.
#'
#' @param color_label Legend title used by the default grid color scale.
#'
#' @param line_color Color of the central trajectory for grid-summary plots.
#'
#' @param ribbon_fill,ribbon_alpha Fill and transparency of the uncertainty
#'   ribbon for grid-summary plots.
#'
#' @param show_ribbon Logical. If `TRUE`, a grid-summary plot shows the
#'   uncertainty ribbon when lower and upper columns are available.
#'
#' @param smooth Logical. For grid plots, use `ggplot2::geom_smooth()` when
#'   `TRUE` (default) or `ggplot2::geom_line()` when `FALSE`.
#'
#' @param smooth_method Optional smoothing method passed to
#'   `ggplot2::geom_smooth()`. When `NULL`, ggplot2 chooses its default method.
#'
#' @param smooth_formula Optional formula passed to `ggplot2::geom_smooth()`.
#'
#' @param smooth_se Logical. Display the smoothing standard-error band produced
#'   by `geom_smooth()`. Default is `FALSE`. This is distinct from the
#'   prediction uncertainty represented by `lower` and `upper`.
#'
#' @param line_width Optional positive line width for grid trajectories.
#'   When `NULL`, ggplot2 uses its default.
#'
#' @param line_alpha Transparency of grid trajectories, between 0 and 1.
#'
#' @param paired_samples_geom Character. Geometry used when
#'   `scenario_type = "paired"` and `output = "samples"`.
#'   `"boxplot"` (default) displays the distribution of the sample predictions
#'   for each paired scenario; `"jitter"` displays the individual sample
#'   predictions.
#'
#' @param boxplot_color,boxplot_fill Color and fill used by the default paired
#'   sample boxplot.
#'
#' @param boxplot_width Optional positive box width for paired sample boxplots.
#'   When `NULL`, ggplot2 uses its default.
#'
#' @param jitter_color Color used for paired sample jittered points.
#'
#' @param jitter_width Horizontal jitter width for paired sample points.
#'
#' @param jitter_alpha Transparency of paired sample jittered points.
#'
#' @param jitter_size Optional positive size of paired sample jittered points.
#'   When `NULL`, ggplot2 uses its default.
#'
#' @param pointrange_color Color used by `ggplot2::geom_pointrange()` for paired
#'   summary plots.
#'
#' @param point_size Optional positive point size for paired-summary plots.
#'   When `NULL`, ggplot2 uses its default.
#'
#' @param pointrange_linewidth Optional positive line width for the uncertainty
#'   interval in paired-summary plots. When `NULL`, ggplot2 uses its default.
#'
#' @param paired_x_discrete Logical. For paired scenarios, treat the x variable
#'   as discrete when `TRUE` (default), matching a manual mapping such as
#'   `aes(as.factor(rain), ...)`. If `FALSE`, `x` must be numeric and a
#'   continuous x-axis is used.
#'
#' @param x_breaks,y_breaks Axis breaks. Defaults to `ggplot2::waiver()`, which
#'   lets ggplot2 choose breaks automatically and preserves axis tick labels and
#'   the `theme_bw()` panel grid. Use `NULL` only to intentionally remove the
#'   corresponding breaks and grid lines.
#'
#' @param x_limits,y_limits Optional axis limits.
#'
#'   For grid plots and paired plots with `paired_x_discrete = FALSE`,
#'   `x_limits` must be a finite numeric vector of length two.
#'
#'   For paired plots with `paired_x_discrete = TRUE`, `x_limits` can instead be
#'   a vector of observed x levels used to subset and/or order the displayed
#'   categories.
#'
#' @param x_expand,y_expand Axis expansion specifications.
#'
#'   When `x_expand = NULL`, continuous x-axes use
#'   `ggplot2::expansion(mult = c(0.01, 0.01))`, matching the original
#'   EpiExposure scenario figure, while discrete paired x-axes retain ggplot2's
#'   default discrete expansion.
#'
#' @param x_label,y_label Axis titles. Defaults are `"Exposure"` and
#'   `"Predicted"`.
#'
#' @param title,subtitle,caption Optional plot annotations.
#'
#' @param theme Optional ggplot2 theme added after the default `theme_bw()` and
#'   EpiExposure text settings, allowing users to override them.
#'
#' @param base_size Base text size. Default is 10.
#'
#' @param text_face Common text face. Default is `"bold"`.
#'
#' @param axis_title_size Axis-title size. Default is 12.
#'
#' @param strip_background Facet-strip background element.
#'
#' @param legend_position Legend position. Default is `"none"`.
#'
#' @param line_args Optional named list of additional arguments passed to the
#'   active grid trajectory layer (`geom_smooth()` or `geom_line()`).
#'
#' @param ribbon_args Optional named list of additional arguments passed to
#'   `ggplot2::geom_ribbon()` in grid-summary mode.
#'
#' @param boxplot_args Optional named list of additional arguments passed to
#'   `ggplot2::geom_boxplot()` in paired-samples mode.
#'
#' @param jitter_args Optional named list of additional arguments passed to
#'   `ggplot2::geom_jitter()` when `paired_samples_geom = "jitter"`.
#'
#' @param pointrange_args Optional named list of additional arguments passed to
#'   `ggplot2::geom_pointrange()` in paired-summary mode.
#'
#' @param point_args Optional named list of additional arguments passed to
#'   `ggplot2::geom_point()` when summary predictions do not contain lower/upper
#'   uncertainty limits.
#'
#' @param add Optional ggplot2 component or list of components added last.
#'
#' @param ... Additional named arguments passed to the principal geometry used
#'   for the selected combination of `scenario_type` and `output`.
#'
#' @return A `ggplot` object.
#'
#' @details
#' `scenario_type` and `output` describe different aspects of the data and
#' should not be conflated:
#'
#' * `scenario_type` describes how exposure scenarios were constructed by
#'   `simulate_ranges()`.
#' * `output` describes how predictions were returned by
#'   `simulate_scenarios()`.
#'
#' Consequently, all four combinations are valid.
#'
#' For sample-level output, `lower` and `upper` are intentionally ignored. The
#' uncertainty is represented by the multiple sample predictions themselves.
#'
#' For summary output, lower and upper limits are used when available:
#'
#' * grid + summary: the limits define the uncertainty ribbon;
#' * paired + summary: the limits define the vertical point-range.
#'
#' If summary output does not contain lower/upper limits, the function still
#' plots the central prediction: a grid trajectory for grid scenarios or
#' points for paired scenarios.
#'
#' For paired sample output, `geom_boxplot()` is the default because several
#' prediction samples correspond to the same paired scenario value. The user
#' can instead request the individual sample predictions with
#' `paired_samples_geom = "jitter"`.
#'
#' @examples
#' \dontrun{
#' # -----------------------------------------------------------------------
#' # 1. GRID + SAMPLES
#' # -----------------------------------------------------------------------
#' pred_grid_samples <- simulate_scenarios(
#'   fit = fit,
#'   scenarios = range_grid,
#'   data = sim_data,
#'   uncertainty = TRUE,
#'   output = "samples",
#'   n_samples = 20,
#'   seed = 1234
#' )
#'
#' plot_scenarios(
#'   data = pred_grid_samples,
#'   x = "rain",
#'   scenario_type = "grid",
#'   output = "samples",
#'   facet = c("wetness", "tmean"),
#'   scale_factor = 100,
#'   x_limits = c(0, 15)
#' )
#'
#' # Because output = "auto" is the default, the same plot can be requested as:
#' plot_scenarios(
#'   data = pred_grid_samples,
#'   x = "rain",
#'   scenario_type = "grid",
#'   facet = c("wetness", "tmean"),
#'   scale_factor = 100,
#'   x_limits = c(0, 15)
#' )
#'
#' # -----------------------------------------------------------------------
#' # 2. GRID + SUMMARY
#' # -----------------------------------------------------------------------
#' plot_scenarios(
#'   data = pred_grid_summary,
#'   x = "rain",
#'   scenario_type = "grid",
#'   output = "summary",
#'   facet = c("wetness", "tmean"),
#'   scale_factor = 100
#' )
#'
#' # -----------------------------------------------------------------------
#' # 3. PAIRED + SAMPLES
#' # -----------------------------------------------------------------------
#' plot_scenarios(
#'   data = pred_paired_samples,
#'   x = "rain",
#'   scenario_type = "paired",
#'   output = "samples",
#'   scale_factor = 100,
#'   x_label = "Daily precipitation (mm)",
#'   y_label = "Predicted (%)"
#' )
#'
#' # Show the individual sample predictions instead of boxplots:
#' plot_scenarios(
#'   data = pred_paired_samples,
#'   x = "rain",
#'   scenario_type = "paired",
#'   output = "samples",
#'   paired_samples_geom = "jitter",
#'   scale_factor = 100
#' )
#'
#' # -----------------------------------------------------------------------
#' # 4. PAIRED + SUMMARY
#' # -----------------------------------------------------------------------
#' plot_scenarios(
#'   data = pred_paired_summary,
#'   x = "rain",
#'   scenario_type = "paired",
#'   output = "summary",
#'   scale_factor = 100,
#'   x_label = "Daily precipitation (mm)",
#'   y_label = "Predicted (%)"
#' )
#' }
#'
#' @export
plot_scenarios <- function(
    data,
    x,
    scenario_type = c("grid", "paired"),
    output = c("auto", "samples", "summary"),
    mode = NULL,
    y = "prediction",
    facet = NULL,
    sample = "sample",
    lower = NULL,
    upper = NULL,
    scale_factor = 1,
    facet_ncol = NULL,
    facet_nrow = NULL,
    color_scale = NULL,
    color_label = "Sample",
    line_color = "black",
    ribbon_fill = "grey70",
    ribbon_alpha = 0.25,
    show_ribbon = TRUE,
    smooth = TRUE,
    smooth_method = NULL,
    smooth_formula = NULL,
    smooth_se = FALSE,
    line_width = NULL,
    line_alpha = 1,
    paired_samples_geom = c("boxplot", "jitter"),
    boxplot_color = "black",
    boxplot_fill = "white",
    boxplot_width = NULL,
    jitter_color = "black",
    jitter_width = 0.12,
    jitter_alpha = 0.65,
    jitter_size = NULL,
    pointrange_color = "black",
    point_size = NULL,
    pointrange_linewidth = NULL,
    paired_x_discrete = TRUE,
    x_breaks = ggplot2::waiver(),
    y_breaks = ggplot2::waiver(),
    x_limits = NULL,
    y_limits = NULL,
    x_expand = NULL,
    y_expand = ggplot2::waiver(),
    x_label = "Exposure",
    y_label = "Predicted",
    title = NULL,
    subtitle = NULL,
    caption = NULL,
    theme = NULL,
    base_size = 10,
    text_face = "bold",
    axis_title_size = 12,
    strip_background = ggplot2::element_rect(
      fill = "white",
      colour = "black"
    ),
    legend_position = "none",
    line_args = list(),
    ribbon_args = list(),
    boxplot_args = list(),
    jitter_args = list(),
    pointrange_args = list(),
    point_args = list(),
    add = NULL,
    ...
) {
  if (!requireNamespace("ggplot2", quietly = TRUE)) {
    stop(
      "Package 'ggplot2' is required by `plot_scenarios()`.",
      call. = FALSE
    )
  }

  # -------------------------------------------------------------------------
  # Small internal validators/helpers
  # -------------------------------------------------------------------------

  scalar_name <- function(z) {
    is.character(z) &&
      length(z) == 1L &&
      !is.na(z) &&
      nzchar(z)
  }

  scalar_name_or_null <- function(z) {
    is.null(z) || scalar_name(z)
  }

  scalar_flag <- function(z) {
    is.logical(z) &&
      length(z) == 1L &&
      !is.na(z)
  }

  positive_number_or_null <- function(z, argument) {
    if (is.null(z)) {
      return(NULL)
    }

    if (!is.numeric(z) ||
        length(z) != 1L ||
        is.na(z) ||
        !is.finite(z) ||
        z <= 0) {
      stop(
        "`", argument,
        "` must be NULL or one positive finite number.",
        call. = FALSE
      )
    }

    z
  }

  positive_integer_or_null <- function(z, argument) {
    if (is.null(z)) {
      return(NULL)
    }

    if (!is.numeric(z) ||
        length(z) != 1L ||
        is.na(z) ||
        !is.finite(z) ||
        z < 1 ||
        z != as.integer(z)) {
      stop(
        "`", argument,
        "` must be NULL or a positive integer.",
        call. = FALSE
      )
    }

    as.integer(z)
  }

  named_list <- function(z, argument) {
    if (!is.list(z)) {
      stop(
        "`", argument, "` must be a list.",
        call. = FALSE
      )
    }

    if (length(z) &&
        (is.null(names(z)) ||
         anyNA(names(z)) ||
         any(!nzchar(names(z))))) {
      stop(
        "Every entry in `", argument, "` must be named.",
        call. = FALSE
      )
    }

    z
  }

  add_components <- function(plot_object, components) {
    if (is.null(components)) {
      return(plot_object)
    }

    if (!is.list(components) ||
        inherits(
          components,
          c("gg", "ggplot", "Scale", "theme", "Coord")
        )) {
      components <- list(components)
    }

    for (component in components) {
      plot_object <- plot_object + component
    }

    plot_object
  }

  is_waiver <- function(z) {
    inherits(z, "waiver")
  }

  resolve_interval_column <- function(
    requested,
    candidates,
    role,
    data_names
  ) {
    if (!is.null(requested)) {
      if (!requested %in% data_names) {
        stop(
          "The ", role, " interval column '", requested,
          "' was not found in `data`.",
          call. = FALSE
        )
      }

      return(requested)
    }

    available <- candidates[candidates %in% data_names]

    if (length(available)) {
      return(available[[1L]])
    }

    NULL
  }

  # -------------------------------------------------------------------------
  # Basic data and argument validation
  # -------------------------------------------------------------------------

  if (!is.data.frame(data) || !nrow(data)) {
    stop(
      "`data` must be a non-empty data frame returned by ",
      "`simulate_scenarios()`.",
      call. = FALSE
    )
  }

  if (!scalar_name(x)) {
    stop(
      "`x` must be one non-empty column name.",
      call. = FALSE
    )
  }

  if (!scalar_name(y)) {
    stop(
      "`y` must be one non-empty column name.",
      call. = FALSE
    )
  }

  if (!scalar_name(sample)) {
    stop(
      "`sample` must be one non-empty column name.",
      call. = FALSE
    )
  }

  if (!scalar_name_or_null(lower)) {
    stop(
      "`lower` must be NULL or one non-empty column name.",
      call. = FALSE
    )
  }

  if (!scalar_name_or_null(upper)) {
    stop(
      "`upper` must be NULL or one non-empty column name.",
      call. = FALSE
    )
  }

  if (!is.null(facet) &&
      (!is.character(facet) ||
       !length(facet) ||
       anyNA(facet) ||
       any(!nzchar(facet)) ||
       anyDuplicated(facet))) {
    stop(
      "`facet` must be NULL or unique non-empty column names.",
      call. = FALSE
    )
  }

  scenario_type <- match.arg(scenario_type)

  # `mode` is kept only as a compatibility alias for the old API.
  if (!is.null(mode)) {
    if (!missing(output)) {
      stop(
        "Use only one of `output` or the legacy `mode` argument, not both.",
        call. = FALSE
      )
    }

    if (!is.character(mode) ||
        length(mode) != 1L ||
        is.na(mode) ||
        !mode %in% c("auto", "samples", "summary")) {
      stop(
        "`mode` must be NULL, \"auto\", \"samples\", or \"summary\".",
        call. = FALSE
      )
    }

    output <- mode
  } else {
    output <- match.arg(output)
  }

  paired_samples_geom <- match.arg(paired_samples_geom)

  for (argument in c(
    "show_ribbon",
    "smooth",
    "smooth_se",
    "paired_x_discrete"
  )) {
    if (!scalar_flag(get(argument, inherits = FALSE))) {
      stop(
        "`", argument, "` must be TRUE or FALSE.",
        call. = FALSE
      )
    }
  }

  if (!is.numeric(scale_factor) ||
      length(scale_factor) != 1L ||
      is.na(scale_factor) ||
      !is.finite(scale_factor)) {
    stop(
      "`scale_factor` must be one finite number.",
      call. = FALSE
    )
  }

  if (!is.numeric(line_alpha) ||
      length(line_alpha) != 1L ||
      is.na(line_alpha) ||
      !is.finite(line_alpha) ||
      line_alpha < 0 ||
      line_alpha > 1) {
    stop(
      "`line_alpha` must be between 0 and 1.",
      call. = FALSE
    )
  }

  if (!is.numeric(ribbon_alpha) ||
      length(ribbon_alpha) != 1L ||
      is.na(ribbon_alpha) ||
      !is.finite(ribbon_alpha) ||
      ribbon_alpha < 0 ||
      ribbon_alpha > 1) {
    stop(
      "`ribbon_alpha` must be between 0 and 1.",
      call. = FALSE
    )
  }

  if (!is.numeric(jitter_alpha) ||
      length(jitter_alpha) != 1L ||
      is.na(jitter_alpha) ||
      !is.finite(jitter_alpha) ||
      jitter_alpha < 0 ||
      jitter_alpha > 1) {
    stop(
      "`jitter_alpha` must be between 0 and 1.",
      call. = FALSE
    )
  }

  if (!is.numeric(jitter_width) ||
      length(jitter_width) != 1L ||
      is.na(jitter_width) ||
      !is.finite(jitter_width) ||
      jitter_width < 0) {
    stop(
      "`jitter_width` must be one non-negative finite number.",
      call. = FALSE
    )
  }

  line_width <- positive_number_or_null(
    line_width,
    "line_width"
  )

  boxplot_width <- positive_number_or_null(
    boxplot_width,
    "boxplot_width"
  )

  jitter_size <- positive_number_or_null(
    jitter_size,
    "jitter_size"
  )

  point_size <- positive_number_or_null(
    point_size,
    "point_size"
  )

  pointrange_linewidth <- positive_number_or_null(
    pointrange_linewidth,
    "pointrange_linewidth"
  )

  facet_ncol <- positive_integer_or_null(
    facet_ncol,
    "facet_ncol"
  )

  facet_nrow <- positive_integer_or_null(
    facet_nrow,
    "facet_nrow"
  )

  line_args <- named_list(
    line_args,
    "line_args"
  )

  ribbon_args <- named_list(
    ribbon_args,
    "ribbon_args"
  )

  boxplot_args <- named_list(
    boxplot_args,
    "boxplot_args"
  )

  jitter_args <- named_list(
    jitter_args,
    "jitter_args"
  )

  pointrange_args <- named_list(
    pointrange_args,
    "pointrange_args"
  )

  point_args <- named_list(
    point_args,
    "point_args"
  )

  dots <- named_list(
    list(...),
    "..."
  )

  if (!is.null(color_scale) &&
      !inherits(color_scale, "Scale")) {
    stop(
      "`color_scale` must be NULL or a ggplot2 color scale.",
      call. = FALSE
    )
  }

  # -------------------------------------------------------------------------
  # Resolve the simulate_scenarios() output structure
  # -------------------------------------------------------------------------

  if (output == "auto") {
    output <- if (sample %in% names(data)) {
      "samples"
    } else {
      "summary"
    }
  }

  required <- unique(c(
    x,
    y,
    facet,
    if (output == "samples") sample
  ))

  missing_columns <- setdiff(
    required,
    names(data)
  )

  if (length(missing_columns)) {
    stop(
      "Column(s) missing from `data`: ",
      paste(missing_columns, collapse = ", "),
      ".",
      call. = FALSE
    )
  }

  if (!is.numeric(data[[y]]) ||
      anyNA(data[[y]]) ||
      any(!is.finite(data[[y]]))) {
    stop(
      "Column '", y,
      "' must contain finite numeric values.",
      call. = FALSE
    )
  }

  # Grid scenarios always use a continuous x-axis.
  # Paired scenarios use a discrete x-axis by default.
  if (scenario_type == "grid" ||
      !paired_x_discrete) {
    if (!is.numeric(data[[x]]) ||
        anyNA(data[[x]]) ||
        any(!is.finite(data[[x]]))) {
      stop(
        "Column '", x,
        "' must contain finite numeric values for a continuous x-axis.",
        call. = FALSE
      )
    }
  } else if (anyNA(data[[x]])) {
    stop(
      "Column '", x, "' cannot contain missing values.",
      call. = FALSE
    )
  }

  # -------------------------------------------------------------------------
  # Resolve uncertainty columns ONLY for summary output
  # -------------------------------------------------------------------------

  lower_name <- NULL
  upper_name <- NULL
  has_interval <- FALSE

  if (output == "summary") {
    lower_name <- resolve_interval_column(
      requested = lower,
      candidates = c(
        "prediction_lower",
        "lower"
      ),
      role = "lower",
      data_names = names(data)
    )

    upper_name <- resolve_interval_column(
      requested = upper,
      candidates = c(
        "prediction_upper",
        "upper"
      ),
      role = "upper",
      data_names = names(data)
    )

    if (xor(
      is.null(lower_name),
      is.null(upper_name)
    )) {
      stop(
        "Only one uncertainty-limit column could be identified. ",
        "Both lower and upper limits must be supplied together.",
        call. = FALSE
      )
    }

    has_interval <- !is.null(lower_name) &&
      !is.null(upper_name)

    if (has_interval) {
      for (column in c(
        lower_name,
        upper_name
      )) {
        if (!is.numeric(data[[column]]) ||
            anyNA(data[[column]]) ||
            any(!is.finite(data[[column]]))) {
          stop(
            "Interval column '", column,
            "' must contain finite numeric values.",
            call. = FALSE
          )
        }
      }

      if (any(
        data[[lower_name]] >
        data[[upper_name]]
      )) {
        stop(
          "Every lower interval value must be less than or equal to ",
          "its corresponding upper interval value.",
          call. = FALSE
        )
      }
    }
  }

  # -------------------------------------------------------------------------
  # Prepare plotting variables
  # -------------------------------------------------------------------------

  plot_data <- data

  plot_data$.plot_y <-
    plot_data[[y]] *
    scale_factor

  if (scenario_type == "paired" &&
      paired_x_discrete) {
    raw_x <- plot_data[[x]]

    if (is.factor(raw_x)) {
      x_levels <- levels(
        droplevels(raw_x)
      )
    } else if (is.numeric(raw_x)) {
      x_levels <- as.character(
        sort(unique(raw_x))
      )
    } else {
      x_levels <- unique(
        as.character(raw_x)
      )
    }

    plot_data$.plot_x <- factor(
      as.character(raw_x),
      levels = x_levels
    )
  } else {
    plot_data$.plot_x <-
      plot_data[[x]]
  }

  # This grouping variable is useful for paired boxplots even when x is numeric.
  plot_data$.plot_x_group <- factor(
    as.character(plot_data[[x]]),
    levels = unique(as.character(plot_data[[x]]))
  )

  if (output == "samples") {
    sample_values <-
      plot_data[[sample]]

    sample_numeric <-
      suppressWarnings(
        as.numeric(
          as.character(sample_values)
        )
      )

    if (anyNA(sample_numeric)) {
      sample_numeric <-
        as.numeric(
          factor(
            sample_values,
            levels = unique(sample_values)
          )
        )
    }

    plot_data$.plot_sample <-
      sample_numeric

    plot_data$.plot_sample_group <-
      plot_data[[sample]]
  }

  if (output == "summary" &&
      has_interval) {
    plot_data$.plot_lower <-
      plot_data[[lower_name]] *
      scale_factor

    plot_data$.plot_upper <-
      plot_data[[upper_name]] *
      scale_factor
  }

  # -------------------------------------------------------------------------
  # Build the selected scenario/output plot
  # -------------------------------------------------------------------------

  plot_object <-
    ggplot2::ggplot(plot_data)

  # =========================================================================
  # GRID
  # =========================================================================

  if (scenario_type == "grid") {
    # -----------------------------------------------------------------------
    # GRID + SUMMARY: uncertainty ribbon when available
    # -----------------------------------------------------------------------
    if (output == "summary" &&
        show_ribbon &&
        has_interval) {
      ribbon_layer <- list(
        mapping = ggplot2::aes(
          x = .data$.plot_x,
          ymin = .data$.plot_lower,
          ymax = .data$.plot_upper
        ),
        fill = ribbon_fill,
        alpha = ribbon_alpha,
        inherit.aes = FALSE
      )

      ribbon_layer[
        names(ribbon_args)
      ] <- ribbon_args

      plot_object <-
        plot_object +
        do.call(
          ggplot2::geom_ribbon,
          ribbon_layer
        )
    }

    # -----------------------------------------------------------------------
    # GRID + SAMPLES or GRID + SUMMARY: central trajectories
    # -----------------------------------------------------------------------
    trajectory_args <- dots

    trajectory_args[
      names(line_args)
    ] <- line_args

    trajectory_args$alpha <-
      line_alpha

    if (!is.null(line_width)) {
      trajectory_args$linewidth <-
        line_width
    }

    if (output == "samples") {
      trajectory_args$mapping <-
        ggplot2::aes(
          x = .data$.plot_x,
          y = .data$.plot_y,
          group = .data$.plot_sample_group,
          colour = .data$.plot_sample
        )
    } else {
      trajectory_args$mapping <-
        ggplot2::aes(
          x = .data$.plot_x,
          y = .data$.plot_y
        )

      trajectory_args$colour <-
        line_color
    }

    if (smooth) {
      trajectory_args$se <-
        smooth_se

      if (!is.null(smooth_method)) {
        trajectory_args$method <-
          smooth_method
      }

      if (!is.null(smooth_formula)) {
        trajectory_args$formula <-
          smooth_formula
      }

      plot_object <-
        plot_object +
        do.call(
          ggplot2::geom_smooth,
          trajectory_args
        )
    } else {
      trajectory_args$se <- NULL

      plot_object <-
        plot_object +
        do.call(
          ggplot2::geom_line,
          trajectory_args
        )
    }

    if (output == "samples") {
      if (is.null(color_scale)) {
        color_scale <-
          ggplot2::scale_color_viridis_c(
            name = color_label
          )
      }

      plot_object <-
        plot_object +
        color_scale
    }
  }

  # =========================================================================
  # PAIRED
  # =========================================================================

  if (scenario_type == "paired") {
    # -----------------------------------------------------------------------
    # PAIRED + SAMPLES
    #
    # No lower/upper limits exist here. The multiple sample predictions
    # themselves represent the uncertainty distribution.
    # -----------------------------------------------------------------------
    if (output == "samples") {
      if (paired_samples_geom == "boxplot") {
        box_layer <- dots

        box_layer[
          names(boxplot_args)
        ] <- boxplot_args

        box_layer$mapping <-
          ggplot2::aes(
            x = .data$.plot_x,
            y = .data$.plot_y,
            group = .data$.plot_x_group
          )

        box_layer$colour <-
          boxplot_color

        box_layer$fill <-
          boxplot_fill

        if (!is.null(boxplot_width)) {
          box_layer$width <-
            boxplot_width
        }

        plot_object <-
          plot_object +
          do.call(
            ggplot2::geom_boxplot,
            box_layer
          )
      }

      if (paired_samples_geom == "jitter") {
        jitter_layer <- dots

        jitter_layer[
          names(jitter_args)
        ] <- jitter_args

        jitter_layer$mapping <-
          ggplot2::aes(
            x = .data$.plot_x,
            y = .data$.plot_y
          )

        jitter_layer$colour <-
          jitter_color

        jitter_layer$width <-
          jitter_width

        jitter_layer$alpha <-
          jitter_alpha

        if (!is.null(jitter_size)) {
          jitter_layer$size <-
            jitter_size
        }

        plot_object <-
          plot_object +
          do.call(
            ggplot2::geom_jitter,
            jitter_layer
          )
      }
    }

    # -----------------------------------------------------------------------
    # PAIRED + SUMMARY
    #
    # With prediction_lower/prediction_upper -> geom_pointrange()
    # Without intervals -> geom_point()
    # -----------------------------------------------------------------------
    if (output == "summary") {
      if (has_interval) {
        pointrange_layer <- dots

        pointrange_layer[
          names(pointrange_args)
        ] <- pointrange_args

        pointrange_layer$mapping <-
          ggplot2::aes(
            x = .data$.plot_x,
            y = .data$.plot_y,
            ymin = .data$.plot_lower,
            ymax = .data$.plot_upper
          )

        pointrange_layer$colour <-
          pointrange_color

        if (!is.null(point_size)) {
          pointrange_layer$size <-
            point_size
        }

        if (!is.null(
          pointrange_linewidth
        )) {
          pointrange_layer$linewidth <-
            pointrange_linewidth
        }

        plot_object <-
          plot_object +
          do.call(
            ggplot2::geom_pointrange,
            pointrange_layer
          )
      } else {
        point_layer <- dots

        point_layer[
          names(point_args)
        ] <- point_args

        point_layer$mapping <-
          ggplot2::aes(
            x = .data$.plot_x,
            y = .data$.plot_y
          )

        point_layer$colour <-
          pointrange_color

        if (!is.null(point_size)) {
          point_layer$size <-
            point_size
        }

        plot_object <-
          plot_object +
          do.call(
            ggplot2::geom_point,
            point_layer
          )
      }
    }
  }

  # -------------------------------------------------------------------------
  # Shared labels and theme
  # -------------------------------------------------------------------------

  plot_object <-
    plot_object +
    ggplot2::theme_bw() +
    ggplot2::labs(
      x = x_label,
      y = y_label,
      title = title,
      subtitle = subtitle,
      caption = caption
    ) +
    ggplot2::theme(
      text = ggplot2::element_text(
        size = base_size,
        face = text_face
      ),
      axis.title = ggplot2::element_text(
        size = axis_title_size,
        face = text_face
      ),
      strip.background =
        strip_background,
      legend.position =
        legend_position
    )

  # -------------------------------------------------------------------------
  # Facets
  # -------------------------------------------------------------------------

  if (length(facet)) {
    facet_formula <-
      stats::reformulate(facet)

    plot_object <-
      plot_object +
      ggplot2::facet_wrap(
        facet_formula,
        ncol = facet_ncol,
        nrow = facet_nrow
      )
  }

  # -------------------------------------------------------------------------
  # X axis
  # -------------------------------------------------------------------------

  if (is.null(x_expand)) {
    if (scenario_type == "paired" &&
        paired_x_discrete) {
      x_expand_use <-
        ggplot2::waiver()
    } else {
      x_expand_use <-
        ggplot2::expansion(
          mult = c(
            0.01,
            0.01
          )
        )
    }
  } else {
    x_expand_use <-
      x_expand
  }

  if (scenario_type == "paired" &&
      paired_x_discrete) {
    observed_levels <-
      levels(
        plot_data$.plot_x
      )

    x_breaks_use <-
      x_breaks

    if (!is.null(x_breaks_use) &&
        !is_waiver(x_breaks_use)) {
      x_breaks_use <-
        as.character(
          x_breaks_use
        )

      unknown_breaks <-
        setdiff(
          x_breaks_use,
          observed_levels
        )

      if (length(unknown_breaks)) {
        stop(
          "For a discrete paired x-axis, `x_breaks` must contain observed ",
          "x levels. Unknown level(s): ",
          paste(
            unknown_breaks,
            collapse = ", "
          ),
          ".",
          call. = FALSE
        )
      }
    }

    x_limits_use <-
      x_limits

    if (!is.null(x_limits_use)) {
      x_limits_use <-
        as.character(
          x_limits_use
        )

      unknown_limits <-
        setdiff(
          x_limits_use,
          observed_levels
        )

      if (length(unknown_limits)) {
        stop(
          "For `scenario_type = \"paired\"` with ",
          "`paired_x_discrete = TRUE`, `x_limits` specifies displayed ",
          "scenario levels, not numeric axis boundaries. Unknown level(s): ",
          paste(
            unknown_limits,
            collapse = ", "
          ),
          ". Observed levels are: ",
          paste(
            observed_levels,
            collapse = ", "
          ),
          ".",
          call. = FALSE
        )
      }
    }

    plot_object <-
      plot_object +
      ggplot2::scale_x_discrete(
        breaks = x_breaks_use,
        limits = x_limits_use,
        expand = x_expand_use
      )
  } else {
    if (!is.null(x_limits) &&
        (!is.numeric(x_limits) ||
         length(x_limits) != 2L ||
         anyNA(x_limits) ||
         any(!is.finite(x_limits)))) {
      stop(
        "`x_limits` must be NULL or a finite numeric vector of length two ",
        "for a continuous x-axis.",
        call. = FALSE
      )
    }

    plot_object <-
      plot_object +
      ggplot2::scale_x_continuous(
        breaks = x_breaks,
        limits = x_limits,
        expand = x_expand_use
      )
  }

  # -------------------------------------------------------------------------
  # Y axis
  # -------------------------------------------------------------------------

  if (!is.null(y_limits) &&
      (!is.numeric(y_limits) ||
       length(y_limits) != 2L ||
       anyNA(y_limits) ||
       any(!is.finite(y_limits)))) {
    stop(
      "`y_limits` must be NULL or a finite numeric vector of length two.",
      call. = FALSE
    )
  }

  plot_object <-
    plot_object +
    ggplot2::scale_y_continuous(
      breaks = y_breaks,
      limits = y_limits,
      expand = y_expand
    )

  # -------------------------------------------------------------------------
  # User overrides and additions
  # -------------------------------------------------------------------------

  if (!is.null(theme)) {
    plot_object <-
      plot_object +
      theme
  }

  add_components(
    plot_object,
    add
  )
}
